# La tecnología en la industria minera: La convidada de piedra.

Al momento de escribir esta columna (febrero, 2020), Chuquicamata está – ad portas – de cumplir 10 meses operando su nueva mina subterránea. Sin duda, esto es un hito de gran relevancia para la minería chilena. Desafortunadamente, este acontecimiento viene de la mano con la destrucción de miles de empleos debido a la transición desde la mina rajo a la subterránea (ver referencia [1]). El caso de Chuquicamata no es único, representando un ejemplo que se irá repitiendo en los años venideros. Está columna tiene como propósito explicar el trasfondo de esta situación, la cual luce, a simple vista, lamentable.

Es innegable que con el paso del tiempo las operaciones mineras han reducido su intensidad en número de trabajadores de manera persistente. La imagen que acompaña esta columna ilustra a innumerables mineros – o garimpeiros – atraídos por la fiebre del oro en los años 80s , quienes explotaban la mina Serra Pelada en Brasil con herramientas rudimentarias. Sin embargo, cuatro décadas después, el contraste es dramáticamente notorio.

El proceso productivo se ha profesionalizado y la seguridad se ha posicionado como el valor principal en casi todos los países del mundo, o al menos, en los de mayor tradición minera. El proceso productivo se ha divido en etapas, emulando un proceso de manufactura, con el objetivo de extraer minerales para convertirlos en un commodity de la manera más eficientemente posible. Para conseguir dicho propósito, cada minera optimiza concienzudamente sus equipos y dotaciones cada año, presionando los números a la baja de una manera planificada. Entonces, si tenemos en mente la foto antes mencionada, el número de personas se ha reducido de manera impresionante.

Una de las explicaciones que podemos esgrimir para este fenómeno es la brusca intromisión de la tecnología.

Gran parte de las innovaciones tecnológicas implementadas en diversas industrias tienen la capacidad de llevar a cabo tareas mecánicas y manuales de una manera superlativa, prescindiendo de personas para su concreción. Cuando las tareas son repetitivas, estas tienen una mayor probabilidad de ser automatizadas, trayendo consigo destrucción de empleos y temor social. Una paranoia que ha acompañado al hombre desde que las fábricas nacieron en la revolución industrial en la Gran Bretaña del Siglo XVIII.

Es importante resaltar que la tecnología es un concepto mucho más amplio que la automatización o robotización de equipos móviles. Tiene que ver también con la implementación de un conjunto de técnicas con capacidad de transformar la actividad en su totalidad. La puesta en marcha de Chuquicamata Subterránea es en sí misma una nueva tecnología debido a todas las nuevas técnicas incorporadas. Por ejemplo, es posible mencionar el cambio del layout de producción de Panel Caving a Macrobloques, avances en materia de pre-acondicionamiento del macizo rocoso, complejos modelos numéricos para predecir el hundimiento y el reemplazo de camiones (equipos intensivos en mano de obra) por correas transportadoras de última generación (más rápidas y de mayor confiabilidad).

Con el término del super-ciclo de los commodities como escenario de fondo (lapso que comprende los años 2003 hasta el 2013 [2]), los costos de operación que se habían disparado en época de bonanza, rápidamente debieron ponerse a tono a las nuevas circunstancias. Fue allí cuando una convidada de piedra comenzaba a presentarse de manera decidida en las conversaciones sin calurosas bienvenidas: La Tecnología.

La minería es reticente y tradicional. Implementar algo nuevo siempre pareciera ser una tortura y las conversaciones para cambiar un modo productivo involucran a muchos “interesados” (ejecutivos y sindicatos), donde nadie quiere asumir platos rotos si las variaciones no van acorde a los esperado. Pero la tecnología sedujo de una manera sigilosa a los actores del mercado de minerales. Su penetración fue inevitable: su oferta de valor era ser cada vez más barata y no tomarla era el nuevo futuro riesgo. Es así como con el paso de los años el costo relativo del capital tecnológico disminuyó considerablemente respecto al capital salarial.

En palabras simples, esto significa que: ¡el costo de la tecnología se ha vuelto más barato con respecto a los sueldos! (ver Modelo (1))

Por consecuencia, dentro de la última década, muchas compañías grandes – entre ellas, Codelco Chuquicamata – tomaron la decisión de invertir en capital tecnológico y operar sus faenas con nuevas invenciones que el mercado ofrecía. ¿Cuál fue la consecuencia? Una vez adoptadas las tecnologías, la dotación operacional se redujo para siempre en las faenas. 

¿Por qué para siempre? Por ejemplo, según datos del INE, entre el año 2014 – cuando el precio del cobre inició su tendencia a la baja – y el año 2018, se perdieron cerca de 35,000 empleos en minería (ver referencia [3]). Esta tasa de destrucción de empleos no ha cambiado su curso – ni menos ha disminuido – a pesar de que el precio del cobre se ha venido recuperando desde el segundo semestre de 2017.

Muchos analistas podrían sugerir que nuestra concepción sobre la irrecuperable pérdida de empleos debido a la tecnología es errado, argumentando que: "...la caída del precio del cobre se traduce en la destrucción de 1,600 empleos propios en mina Chuquicamata".

Retóricamente podríamos preguntarnos: Si el precio del cobre fuera el real culpable, entonces, ¿por qué al subir los precios no se recuperan la misma cantidad de empleos destruidos?

El fenómeno de reemplazo del capital tecnológico por trabajadores no pareciera tener relación alguna con el precio de los commodities como sugiere nuestro modelo económico (2). Esa explicación más bien encajaría como respuesta para el desempleo minero en corto plazo, donde, sin duda, una caída en el precio de los metales impulsaría a las compañías mineras a despedir trabajadores y renegociar los contratos de servicios. Sin embargo, esto no explica que los empleos no sean recuperados una vez que el mercado de minerales está al alza. Entonces, la respuesta sugerida es que estos trabajadores no han recuperado sus puestos de trabajo porque una vez que las compañías mineras han invertido en tecnología, están adaptadas para operar con menos personas.

Como hemos argumentado hasta ahora, y contrario a lo que supone el Senador Pedro Araya (ver referencia [3]), las compañías mineras si tienen fundamentos económicos para implementar automatización en sus faenas y disminuir el número de trabajadores en sus complejos industriales. Esto es especialmente cierto cuando el costo real de la mano de obra es alto comparativamente hablando y creciente a lo largo del tiempo (ver referencia [4]).

La búsqueda constante por la disminución de costos por parte de los entes productivos alienta a los proveedores tecnológicos a reducir el costo relativo al capital tecnológico, el que sostenidamente se va empequeñeciendo con respecto al costo salarial. Quizás es por ello que este fenómeno ha sido más brusco en faenas con salarios reales promedios altos.

Nuestro análisis no pretende ser dramático. La implementación de capital tecnológico también tiene la capacidad de crear empleos e incluso nuevas profesiones. Las áreas de desarrollo de hardware y software se posicionan como los puestos de trabajos más apetecidos y mejor pagados, en un mundo en donde la industria de los datos es incluso más rentable que la del petróleo ( ver referencia [5]).


## Notas de los Autores
(1) Utilizando teoría microeconómica (ver referencia [6]), específicamente, funciones de producción de elasticidad constante de sustitución (ECS), podemos obtener la siguiente relación entre los factores de producción y sus costos.

No alt text provided for this image
No alt text provided for this image
Si L (trabajo)disminuye con respecto a K (capital tecnológico) en una empresa minera, la única posibilidad que mantiene a ambos lados iguales en la ecuación es que, en el lado derecho, v (costo de capital tecnológico) disminuye con respecto a w (costo de la mano de obra).

(2) En nuestro modelo, el precio de los metales no está involucrado en lo absoluto. Esto sustenta nuestra aseveración de que el precio de los metales no es la razón de la destrucción de empleos sustentada en el tiempo, sino más bien, a un capital tecnológico que ha sido incorporado con fuerza en la actividad minera en la última década y que permite que las compañías mineras operen con una menor dotación. Más aun, un aumento del costo salarial real podría haber acelerado este proceso.

 

## Referencias
[1]     Radio-Infinita.cl, Automatización y tres niveles de profundidad: Así es la nueva Chuquicamata, Http://Www.Infinita.Cl/Home/. (2019). http://www.infinita.cl/noticias/4424-automatizacion-y-tres-niveles-de-profundidad-asi-es-la-nueva-chuquicamata.html (accessed February 3, 2020).

[2]     G. Lagos, El superciclo del cobre sus efectos en Chile, Publicación Electrónica. (2013) 1–25. http://www.gustavolagos.cl/uploads/1/2/4/2/12428079/el_superciclo_y_sus_efectos_en_chile_g._lagos_24-6-13_c.pdf.

[3]     Prensa-Parlamentaria, Codelco y plan de despido de 4 mil trabajadores: “es un desprecio a la Región de Antofagasta,” (2019). https://www.senado.cl/codelco-y-plan-de-despido-de-4-mil-trabajadores-es-un-desprecio-a-la/senado/2019-03-28/152204.html.

[4]     D. Hirsh, L. Valdez-Martinez, The Living Wage, August 201, 2017.

[5]     T. Economist, The world’s most valuable resource is no longer oil, but data, The Economist. (2017). https://www.economist.com/leaders/2017/05/06/the-worlds-most-valuable-resource-is-no-longer-oil-but-data (accessed February 3, 2020).

[6]     W. Nicholson, C. Snyder, Microeconomic Theory: Basic Principles and Extensions, South-Western, 2017.